/*
 * generated by Xtext
 */
package org.xtext.example.qdsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class QDslUiModule extends org.xtext.example.qdsl.ui.AbstractQDslUiModule {
	public QDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
