/*
 * generated by Xtext
 */
package org.xtext.example.qdsl.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.qdsl.services.QDslGrammarAccess;

public class QDslParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private QDslGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.xtext.example.qdsl.parser.antlr.internal.InternalQDslParser createParser(XtextTokenStream stream) {
		return new org.xtext.example.qdsl.parser.antlr.internal.InternalQDslParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public QDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(QDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
