/**
 * generated by Xtext
 */
package org.xtext.example.qdsl.ui.contentassist;

import org.xtext.example.qdsl.ui.contentassist.AbstractQDslProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class QDslProposalProvider extends AbstractQDslProposalProvider {
}
